### ISSUE TITLE
website width expand bug

### ISSUE THREAD

**Issue by souravkv** [souravkv/shoewebsite#1]
since the scroll div below on /New route takes extra space , the whole page seems to expand..fix it so that only 100vw exist
![Screenshot from 2024-05-02 01-35-35](https://github.com/souravkv/shoewebsite/assets/64153119/39c62015-f599-4469-a1a9-c6d7b7d298be)

**Comment by abktowa** [comment]
Hello! I might have a solution for this issue and will submit the pull request shortly.

**Comment by souravkv** [comment]
> Hello! I might have a solution for this issue and will submit the pull request shortly.
